export const PRODUCT_REQUEST = "PRODUCT_REQUEST";
export const PRODUCT_FAILURE = "PRODUCT_FAILURE";

export const CATEGORY_REQUEST = "CATEGORY_REQUEST";
export const CATEGORY_FAILURE = "CATEGORY_FAILURE";

export const COLLECTION_REQUEST = "COLLECTION_REQUEST";
export const COLLECTION_FAILURE = "COLLECTION_FAILURE";

export const POST_PRODUCT_SUCCESS = "POST_PRODUCT_SUCCESS";
export const GET_PRODUCT_SUCCESS = "GET_PRODUCT_SUCCESS";
export const DELETE_PRODUCT_SUCCESS = "DELETE_PRODUCT_SUCCESS";
export const PATCH_PRODUCT_SUCCESS = "PATCH_PRODUCT_SUCCESS";

export const POST_CATEGORY_SUCCESS = "POST_CATEGORY_SUCCESS";
export const GET_CATEGORY_SUCCESS = "GET_CATEGORY_SUCCESS";
export const DELETE_CATEGORY_SUCCESS = "DELETE_CATEGORY_SUCCESS";
export const PATCH_CATEGORY_SUCCESS = "PATCH_CATEGORY_SUCCESS";

export const POST_COLLECTION_SUCCESS = "POST_COLLECTION_SUCCESS";
export const GET_COLLECTION_SUCCESS = "GET_COLLECTION_SUCCESS";
export const DELETE_COLLECTION_SUCCESS = "DELETE_COLLECTION_SUCCESS";
export const PATCH_COLLECTION_SUCCESS = "PATCH_COLLECTION_SUCCESS";
